# Generated by Django 3.1.4 on 2020-12-23 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CWH', '0002_quiz_quizcourse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quiz_Quistion',
        ),
    ]
