# Generated by Django 3.1.4 on 2020-12-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CWH', '0003_auto_20201223_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_quistion',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_quistion',
            name='option1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_quistion',
            name='option2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_quistion',
            name='option3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='quiz_quistion',
            name='option4',
            field=models.CharField(max_length=100),
        ),
    ]
